version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jT7RG4k7L
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web.api:
    image: ${DOCKER_REGISTRY-}web-api
    container_name: webapi
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
     - "8081:80"
    build:
      context: .
      dockerfile: eclipse/src/WebApi/Dockerfile

volumes:
  postgres_data:
